website:
  enabled: true
  fullname: "go-app-deployment"
  replicas: 1
  namespace: "go"
  labels:
    app: "go-app"
  image: "public.ecr.aws/e0m9v9o0/devops-cohort-1:latest"
  port: 5678


service:
  name: "go-app-service"
  namespace: "go"
  selector:
    app: "go-app"
  ports:
    - protocol: "TCP"
      port: 5678
  type: "LoadBalancer"

