apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: cloudiepad/go-app-img:v1
        ports:
        - containerPort: 5678



