apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: go
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
      nodePort: 30000  # Choose any available port within the range 30000-32767
  type: NodePort