apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  namespace: {{ .Values.service.namespace | quote }}
spec:
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  type: {{ .Values.service.type | quote }}
